[package]
name = "hsrtreport"
version = "1.0.0"
entrypoint = "hsrtreport/lib.typ"
authors = ["Frederik Beimgraben"]
license = "CC-BY-SA-4.0"
description = "Report template of the Faculty of Informatics, Reutlingen University"
categories = ["paper", "thesis"]
disciplines = ["computer-science", "engineering"]
